
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: production
spec:
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce

