apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jobber-queue-hpa
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jobber-queue
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Pods
      pods:
        metric:
          name: queue_emroty
        target:
          type: AverageValue
          averageValue: "60"
