apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobber-postgres
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobber-postgres
  template:
    metadata:
      labels:
        app: jobber-postgres
    spec:
      serviceAccountName: jobber-secret-reader
      terminationGracePeriodSeconds: 10
      containers:
      - name: jobber-postgres
        image: postgres:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: jobber-backend-secret
              key: jobber-postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jobber-backend-secret
              key: jobber-postgres-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: jobber-backend-secret
              key: jobber-postgres-db
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources:
          limits:
            memory: "1Gi"
            cpu: "0.5"
          requests:
            cpu: 100m
            memory: 150Mi
        ports:
        - name: jobber-postgres
          containerPort: 5432
        volumeMounts:
        - name: postgres-local-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        - name: secrets-store
          mountPath: /mnt/secrets-store
          readOnly: true    
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - |
                psql -w -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 1"
          initialDelaySeconds: 120
          periodSeconds: 300
          timeoutSeconds: 60
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - |
                psql -w -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 1"
          initialDelaySeconds: 120
          periodSeconds: 300
          timeoutSeconds: 60
      volumes:
      - name: postgres-local-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: jobber-aws-secrets      
