apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: jobber-aws-secrets
  namespace: production
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: "jobber-app-secrets"
        objectType: "secretsmanager"
        jmesPath:
          - path: '"secret-key-one"'
            objectAlias: secret_key_one
          - path: '"secret-key-two"'
            objectAlias: secret_key_two
          - path: '"gateway-jwt-token"'
            objectAlias: gateway_jwt_token
          - path: '"jwt-token"'
            objectAlias: jwt_token
          - path: '"jobber-redis-host"'
            objectAlias: jobber_redis_host
          - path: '"sender-email"'
            objectAlias: sender_email
          - path: '"sender-email-password"'
            objectAlias: sender_email_password
          - path: '"jobber-mysql-db"'
            objectAlias: jobber_mysql_db
          - path: '"MYSQL_ROOT_PASSWORD"'
            objectAlias: mysql-root-pass
          - path: '"MYSQL_PASSWORD"'
            objectAlias: mysql-password
          - path: '"MYSQL_USER"'
            objectAlias: my-sql-user
          - path: '"MYSQL_DATABASE"'
            objectAlias: mysql-database
          - path: '"jobber-postgres-host"'
            objectAlias: jobber_postgres_host
          - path: '"jobber-postgres-user"'
            objectAlias: jobber_postgres_user
          - path: '"jobber-postgres-password"'
            objectAlias: jobber_postgres_password
          - path: '"jobber-postgres-db"'
            objectAlias: jobber_postgres_db
          - path: '"mongo-database-url"'
            objectAlias: mongo_database_url
          - path: '"stripe-api-key"'
            objectAlias: stripe_api_key
          - path: '"stripe-client-key"'
            objectAlias: stripe_client_key
          - path: '"jobber-rabbitmq-user"'
            objectAlias: jobber_rabbitmq_user
          - path: '"jobber-rabbitmq-password"'
            objectAlias: jobber_rabbitmq_password
          - path: '"jobber-rabbitmq-endpoint"'
            objectAlias: jobber_rabbitmq_endpoint
          - path: '"jobber-elasticsearch-url"'
            objectAlias: jobber_elasticsearch_url
          - path: '"jobber-elastic-apm-server-url"'
            objectAlias: jobber_elastic_apm_server_url
          - path: '"jobber-elastic-apm-secret-token"'
            objectAlias: jobber_elastic_apm_secret_token
          - path: '"jobber-elasticsearch-host"'
            objectAlias: jobber_elasticsearch_host
          - path: '"jobber-elasticsearch-username"'
            objectAlias: jobber_elasticsearch_username
          - path: '"jobber-elasticsearch-password"'
            objectAlias: jobber_elasticsearch_password
          - path: '"elasticsearch_service_account_token"'
            objectAlias: elasticsearch_service_account_token
          - path: '"kibana-elasticsearch-password"'
            objectAlias: kibana_elasticsearch_password
          - path: '"redis-username"'
            objectAlias: redis_username  
          - path: '"redis-password"'
            objectAlias: redis_password   
  secretObjects:
    - secretName: jobber-backend-secret
      type: Opaque
      data:
        - objectName: secret_key_one
          key: secret-key-one
        - objectName: secret_key_two
          key: secret-key-two
        - objectName: gateway_jwt_token
          key: gateway-jwt-token
        - objectName: jwt_token
          key: jwt-token
        - objectName: jobber_redis_host
          key: jobber-redis-host
        - objectName: sender_email
          key: sender-email
        - objectName: sender_email_password
          key: sender-email-password
        - objectName: jobber_mysql_db
          key: jobber-mysql-db
        - objectName: mysql-root-pass
          key: MYSQL_ROOT_PASSWORD
        - objectName: mysql-password
          key: MYSQL_PASSWORD
        - objectName: my-sql-user
          key: MYSQL_USER
        - objectName: mysql-database
          key: MYSQL_DATABASE
        - objectName: jobber_postgres_host
          key: jobber-postgres-host
        - objectName: jobber_postgres_user
          key: jobber-postgres-user
        - objectName: jobber_postgres_password
          key: jobber-postgres-password
        - objectName: jobber_postgres_db
          key: jobber-postgres-db
        - objectName: mongo_database_url
          key: mongo-database-url
        - objectName: stripe_api_key
          key: stripe-api-key
        - objectName: stripe_client_key
          key: stripe-client-key
        - objectName: jobber_rabbitmq_user
          key: jobber-rabbitmq-user
        - objectName: jobber_rabbitmq_password
          key: jobber-rabbitmq-password
        - objectName: jobber_rabbitmq_endpoint
          key: jobber-rabbitmq-endpoint
        - objectName: jobber_elasticsearch_url
          key: jobber-elasticsearch-url
        - objectName: jobber_elastic_apm_server_url
          key: jobber-elastic-apm-server-url
        - objectName: jobber_elastic_apm_secret_token
          key: jobber-elastic-apm-secret-token
        - objectName: jobber_elasticsearch_host
          key: jobber-elasticsearch-host
        - objectName: jobber_elasticsearch_username
          key: jobber-elasticsearch-username
        - objectName: jobber_elasticsearch_password
          key: jobber-elasticsearch-password
        - objectName: elasticsearch_service_account_token
          key: elasticsearch_service_account_token
        - objectName: kibana_elasticsearch_password
          key: kibana-elasticsearch-password
        - objectName: redis_username
          key: redis-username
        - objectName: redis_password
          key: redis-password        