apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-users-to-gig
  namespace: production
spec:
  podSelector:
    matchLabels:
      app: jobber-gig
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: jobber-users
        - podSelector:
            matchLabels:
              app: jobber-gateway  
        - podSelector:
           matchLabels:
             app.kubernetes.io/name: prometheus
             app.kubernetes.io/component: server 
        - podSelector:
            matchLabels:
              k8s-app: metricbeat   
        - podSelector:
            matchLabels:
              k8s-app: heartbeat            
