apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-review-to-order
  namespace: production
spec:
  podSelector:
    matchLabels:
      app: jobber-order
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: jobber-review
        - podSelector:
            matchLabels:
              app: jobber-gateway       
