
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: production
spec:
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce

