apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jobber-mongo
  namespace: production
spec:
  selector:
    matchLabels:
      app: jobber-mongo
  serviceName: jobber-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: jobber-mongo
    spec:
      serviceAccountName: jobber-secret-reader
      containers:
      - name: jobber-mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
          name: jobber-mongo
        volumeMounts:
        - name: mongo-local-storage
          mountPath: /data/db
        - name: secrets-store
          mountPath: /mnt/secrets-store
          readOnly: true    
      volumes:
      - name: mongo-local-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
      - name: secrets-store
        csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: jobber-aws-secrets     